### PR TITLE
Update module.json

### PR DESCRIPTION
**Pull request by GregoryWarn**
Added Italian localization

### CODE REVIEW

**Comment by morepurplemorebetter** [comment]
Thank you for this contribution. Unfortunately, because you only translated the dndv3 branch, the module will be missing one entry in the Italian localization file for the main branch. Would you mind also translating the following so I can update both branches (and thus have Italian for all users of this module)?

English:
> The parent item has no limited uses that can be consumed, hence this field is disabled.

This is a tooltip in the overrides dialog to tell the user that they can't set the spell to use charges of the parent item.

EDIT    
For now I'll use the translation that Deepl gave me:
> L' oggetto principale non ha usi limitati che possono essere consumati, quindi questo campo è disattivato.

**Comment by morepurplemorebetter** [comment]
Also, it would've been better if both file changes would be part of the same pull request. You can do that by making the changes in the same branch of the repo on your account. GitHub will then update the pull request with your changes, so I can merge them in one go.

**Comment by GregoryWarn** [comment]
> English:
> > The parent item has no limited uses that can be consumed, hence this field is disabled.
> This is a tooltip in the overrides dialog to tell the user that they can't set the spell to use charges of the parent item.
> EDIT For now I'll use the translation that Deepl gave me:
> > L' oggetto principale non ha usi limitati che possono essere consumati, quindi questo campo è disattivato.

L' oggetto principale non ha usi limitati che possono essere consumati, quindi questo campo è disattivato.
It's a very good translation

**Comment by morepurplemorebetter** [comment]
Great, than I can leave it as is. I'll close this PR, as I already edited the module.json (for both versions). Thank you for adding a translation!

**Pull request closed without merging**
